/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MediaDialog: typeof import('./src/components/MediaDialog.vue')['default']
  }
}
